### ISSUE TITLE
Crashes on Linux (Wayland)

### ISSUE THREAD

**Issue by archseer** [dfrg/swash_demo#2]
Could be a missing dependency somewhere:

```
Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: None, srgb: false }
OpenGL version 4.6 (Core Profile) Mesa 21.3.7
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', swash_demo/src/layout/layout.rs:253:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:729:21
   4: swash_demo::layout::layout::<impl swash_demo::layout::Paragraph>::finish
             at ./src/layout/layout.rs:253:9
   5: swash_demo::layout::builder::ParagraphBuilder::build_into
             at ./src/layout/builder.rs:271:9
   6: swash_demo::main::{{closure}}
             at ./src/main.rs:404:21
   7: winit::platform_impl::platform::sticky_exit_callback
             at /home/speed/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
   8: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at /home/speed/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/event_loop/mod.rs:376:21
   9: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run
             at /home/speed/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/event_loop/mod.rs:191:9
  10: winit::platform_impl::platform::EventLoop<T>::run
             at /home/speed/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:652:56
  11: winit::event_loop::EventLoop<T>::run
             at /home/speed/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  12: swash_demo::main
             at ./src/main.rs:77:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by declantsien** [comment]
I fixed this issue on my Guix by [changing font dir](https://github.com/declantsien/swash_demo/commit/ad4ea65a49935a6147c940c74eb2144857b95cce)
Nix/Guix uses non standard font dirs.
